language: node_js
node_js:
  - lts/*
branches:
  only:
    - main
    - development
addons:
  ssh_known_hosts: git.wpengine.com
script:
  - pushd wp-content/themes/csisjti; npm run build; popd
before_install:
  - openssl aes-256-cbc -K $encrypted_deec70939cbe_key -iv $encrypted_deec70939cbe_iv -in csisjti_rsa.enc -out /tmp/csisjti_rsa -d
  - openssl aes-256-cbc -K $encrypted_bb59d987d74f_key -iv $encrypted_bb59d987d74f_iv -in csisjti_rsa.enc -out /tmp/csisjti_rsa -d
install:
  - pushd wp-content/themes/csisjti; npm install; popd
before_deploy:
  - cd $TRAVIS_BUILD_DIR
deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x deploy-development.sh && sh deploy-development.sh
    on:
      branch: development
  - provider: script
    skip_cleanup: true
    script: chmod +x deploy-staging.sh && sh deploy-staging.sh
    on:
      branch: main
